### PR TITLE
A bunch of cleanup

### PR DESCRIPTION
**Pull request by hhugo**
- remove lwt: making https://github.com/ocsigen/html_of_wiki/issues/71 obsolete
- switch to dune
     - fix https://github.com/ocsigen/html_of_wiki/issues/19
- remove unused code
     - https://github.com/ocsigen/html_of_wiki/issues/100
- cleanup deps
- format the codebase uniformly using ocamlformat mirroring the js_of_ocaml config.  
- restore the build of client.js
- review help page

### CODE REVIEW

**Comment by hhugo** [comment]
I see a JavaScript file `client.js` used in ocsigen.org. How does it relate to client.ml in the repo ?

**Comment by hhugo** [comment]
Also, it's probably better to review commits individually.

**Comment by hhugo** [comment]
Here is the list of unused files. Any plan to use any of them ? Somewhat related to my comment above regarding `client.js`
```
$ ls -l remove-me/
total 64K
-rw-rw-r-- 1 hheuzard tech 6.7K Jan 25 18:05 client.ml
-rw-rw-r-- 1 hheuzard tech 3.4K Jan 25 18:05 compiler.ml
-rw-rw-r-- 1 hheuzard tech 1.3K Jan 25 18:05 crawler.ml
-rw-rw-r-- 1 hheuzard tech  567 Jan 25 18:05 crawler.mli
-rw-rw-r-- 1 hheuzard tech  771 Jan 25 18:05 dot.ml
-rw-rw-r-- 1 hheuzard tech  210 Jan 25 18:04 dot.mli
-rw-rw-r-- 1 hheuzard tech 6.7K Jan 25 18:05 HTML5outliner.ml
-rw-rw-r-- 1 hheuzard tech 4.6K Jan 25 18:05 html_of_wiki.ml
-rw-rw-r-- 1 hheuzard tech 3.5K Jan 25 16:15 linkchecker2json.lisp
-rw-rw-r-- 1 hheuzard tech 3.2K Jan 25 18:05 projects.ml
-rw-rw-r-- 1 hheuzard tech  347 Jan 25 18:05 test.ml
-rw-rw-r-- 1 hheuzard tech 1.5K Jan 25 18:04 wiki_models.mli
-rw-rw-r-- 1 hheuzard tech   81 Jan 25 18:05 wiki_sql.ml
```

**Comment by hhugo** [comment]
cc @leovalais

**Comment by balat** [comment]
client.js is still used by some extensions.
Do not remove it :)

**Comment by balat** [comment]
Le linkchecker peut être utile il me semble ? @leovalais tu peux nous expliquer ?

**Comment by balat** [comment]
Merged (manually)

**Pull request closed without merging**
